apiVersion: dodo.cloud.dodo.cloud/v1
kind: ResourceRenderer
metadata:
  name: resourcerenderer-sample
  namespace: test
spec:
  secretName: test
  secretNamespace: test
  resourceTemplate: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: config
      namespace: test
    data:
      config.yaml: |
        foo: {{ .bar }}
