apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  autoAssign: {{ .Values.autoAssign }}
  addresses:
  - {{ .Values.from }}-{{ .Values.to }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  - {{ .Values.name }}
