apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  namespace: ingress-nginx-private
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/component: controller
  ports:
  - name: lighthouse
    port: 4242
    targetPort: nebula
    protocol: UDP
