apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ui.nebula.lighthouse.name }}
  namespace: {{ .Release.Namespace }}
data:
  lighthouse.yaml: |
    pki:
      ca: /etc/nebula/lighthouse/ca.crt
      cert: /etc/nebula/lighthouse/host.crt
      key: /etc/nebula/lighthouse/host.key
    static_host_map:
      "{{ .Values.ui.nebula.lighthouse.internalIP }}": ["{{ .Values.ui.nebula.lighthouse.externalIP }}:{{ .Values.ui.nebula.lighthouse.port }}"]
    lighthouse:
      am_lighthouse: false
      interval: 60
      hosts:
        - {{ .Values.ui.nebula.lighthouse.internalIP }}
    listen:
      host: "[::]"
      port: 4242
    punchy:
      punch: true
    cipher: chachapoly
    tun:
      disabled: false
      dev: nebula1
      drop_local_broadcast: false
      drop_multicast: false
      tx_queue: 500
      mtu: 1300
    logging:
      level: info
      format: text
    firewall:
      conntrack:
        tcp_timeout: 12m
        udp_timeout: 3m
        default_timeout: 10m
        max_connections: 100000
      outbound:
        - port: any
          proto: any
          host: any
      inbound:
        - port: any
          proto: any
          host: any
