apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: {{ .Release.Namespace }}
spec:
  dependsOn:
    - name: ingress-public
      namespace: {{ .Global.PCloudEnvName }}-ingress-public # TODO(giolekva): derivative
  chart:
    spec:
      chart: charts/cert-manager
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.PCloudEnvName }}
  interval: 1m0s
  timeout: 20m0s
  values:
    fullnameOverride: {{ .Global.PCloudEnvName }}-cert-manager
    installCRDs: true
    image:
      tag: v1.11.1
      pullPolicy: IfNotPresent
