apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certificate-issuer-private
  namespace: {{ .Global.Id }}-ingress-private
spec:
  dependsOn:
  - name: ingress-private
    namespace: {{ .Global.Id }}-ingress-private
  chart:
    spec:
      chart: charts/certificate-issuer-private
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    certManager:
      namespace: {{ .Global.PCloudEnvName }}-cert-manager
      gandiWebhookSecretReader: {{ .Global.PCloudEnvName }}-cert-manager-webhook-gandi
    issuer:
      name: {{ .Global.Id }}-private
      server: https://acme-v02.api.letsencrypt.org/directory
      # server: https://acme-staging-v02.api.letsencrypt.org/directory
      domain: {{ .Global.PrivateDomain }}
      contactEmail: {{ .Global.ContactEmail }}
      gandiAPIToken: {{ .Values.GandiAPIToken }}
