apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certificate-issuer
  namespace: {{ .Global.Id }}
spec:
  # TODO(giolekva): is there better namespace for this?
  targetNamespace: {{ .Global.NamespacePrefix }}ingress-private
  dependsOn:
  - name: ingress-private
    namespace: {{ .Global.Id }}
  chart:
    spec:
      chart: charts/certificate-issuer-public
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    pcloudInstanceId: {{ .Global.Id }}
    certManager:
      namespace: {{ .Global.PCloudEnvName }}-cert-manager
      gandiWebhookSecretReader: {{ .Global.PCloudEnvName }}-cert-manager-webhook-gandi
    issuer:
      name: {{ .Global.Id }}-public
      server: https://acme-v02.api.letsencrypt.org/directory
      # server: https://acme-staging-v02.api.letsencrypt.org/directory
      domain: {{ .Global.Domain }}
      contactEmail: {{ .Global.ContactEmail }}
      ingressClass: {{ .Global.PCloudEnvName }}-ingress-public
