apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-gandi-role
  namespace: {{ .Global.PCloudEnvName }}-cert-manager
spec:
  dependsOn:
    - name: cert-manager
      namespace: {{ .Global.PCloudEnvName }}-cert-manager
  chart:
    spec:
      chart: charts/cert-manager-webhook-gandi-role
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.PCloudEnvName }}
  interval: 1m0s
  timeout: 20m0s
  values:
    certManager:
      namespace: {{ .Global.PCloudEnvName }}-cert-manager
      name: {{ .Global.PCloudEnvName }}-cert-manager
