apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: core-auth-storage
  namespace: {{ .Values.NamespacePrefix }}core-auth
spec:
  chart:
    spec:
      chart: postgresql
      version: 10.13.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: {{ .Values.Id }}
  dependsOn:
  - name: namespaces
    namespace: {{ .Values.Id }}
  interval: 1m0s
  values:
    fullnameOverride: postgres
    image:
      repository: arm64v8/postgres
      tag: 13.4
    service:
      type: ClusterIP
      port: 5432
    postgresqlPassword: psswd
    postgresqlDatabase: kratos
    persistence:
      size: 1Gi
    securityContext:
      enabled: true
      fsGroup: 0
    containerSecurityContext:
      enabled: true
      runAsUser: 0
    volumePermissions:
      securityContext:
        runAsUser: 0
