---
# Source: coredns/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dodo-dns
  namespace: dodo-core-coredns
data:
  dodo.conf: |-
    t10.lekva.me:53 {
        file /etc/dodo/t10.lekva.me.db
        errors
        log
        health {
            lameduck 5s
        }
        ready
        cache 30
        loop
        reload
        loadbalance
    }

    shve.li:53 {
        file /etc/dodo/shve.li.db
        dnssec {
            key file Kshve.li.+013+55992
        }
        errors
        log
        health {
            lameduck 5s
        }
        ready
        cache 30
        loop
        reload
        loadbalance
    }

  shve.li.db:     |
      shve.li.   IN SOA ns1.shve.li. hostmaster.shve.li. 2015082541 7200 3600 1209600 3600
      @ 10800 IN A 65.109.222.108
      * 10800 IN CNAME shve.li.
      p 10800 IN CNAME shve.li.
      *.p 10800 IN A 10.1.0.1

  t10.lekva.me.db:     |
      t10.lekva.me.   IN SOA ns1.lekva.me. hostmaster.lekva.me. 2015082541 7200 3600 1209600 3600
      * 10800 IN CNAME t10.lekva.me.
      @ 10800 IN A 65.109.222.107
      p 10800 IN CNAME t10.lekva.me.
      *.p 10800 IN A 10.1.0.1
