apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: core-auth-storage
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/postgresql
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    fullnameOverride: postgres
    image:
      repository: library/postgres  # arm64v8/postgres
      tag: 15.3
    service:
      type: ClusterIP
      port: 5432
    primary:
      initdb:
        scripts:
          init.sql: |
            CREATE USER kratos WITH PASSWORD 'kratos';
            CREATE USER hydra WITH PASSWORD 'hydra';
            CREATE DATABASE kratos WITH OWNER = kratos;
            CREATE DATABASE hydra WITH OWNER = hydra;
      persistence:
        size: 1Gi
      securityContext:
        enabled: true
        fsGroup: 0
      containerSecurityContext:
        enabled: true
        runAsUser: 0
    volumePermissions:
      securityContext:
        runAsUser: 0
