apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/coredns
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.PCloudEnvName }}
  interval: 1m0s
  values:
    image:
      repository: coredns/coredns
      tag: 1.11.1
      pullPolicy: IfNotPresent
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
    terminationGracePeriodSeconds: 30
    serviceType: "ClusterIP"
    service:
      name: coredns
    serviceAccount:
      create: false
    rbac:
      create: true
      pspEnable: false
    isClusterService: true
    securityContext:
      capabilities:
        add:
          - NET_BIND_SERVICE
    servers:
    - zones:
      - zone: .
      port: 53
      plugins:
      - name: log
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
    extraConfig:
      import:
        parameters: {{ .Values.Volume.MountPath }}/coredns.conf
    extraVolumes:
    - name: zone-configs
      persistentVolumeClaim:
        claimName: {{ .Values.Volume.ClaimName }}
    extraVolumeMounts:
    - name: zone-configs
      mountPath: {{ .Values.Volume.MountPath}}
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1
    zoneFiles: []
    hpa:
      enabled: false
    autoscaler:
      enabled: false
    deployment:
      enabled: true
