apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headscale
  namespace: {{ .Global.NamespacePrefix }}app-headscale
spec:
  chart:
    spec:
      chart: charts/headscale
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    image:
      repository: headscale/headscale
      tag: 0.22.3
      pullPolicy: IfNotPresent
    storage:
      size: 5Gi
    ingressClassName: pcloud-ingress-public
    certificateIssuer: {{ .Global.Id }}-public
    domain: {{ .Values.Subdomain }}.{{ .Global.Doman }}
