apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: namespaces-ingress-private
  namespace: {{ .Global.Id }}
spec:
  chart:
    spec:
      chart: charts/namespaces
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    pcloudInstanceId: {{ .Global.Id }}
    namespacePrefix: {{ .Global.NamespacePrefix }}
    namespaces:
    - ingress-private
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-private
  namespace: {{ .Global.Id }}
spec:
  targetNamespace: {{ .Global.NamespacePrefix }}ingress-private
  dependsOn:
    - name: namespaces-ingress-private
      namespace: {{ .Global.Id }}
  chart:
    spec:
      chart: charts/ingress-nginx
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    fullnameOverride: {{ .Global.Id }}-nginx-private
    controller:
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: {{ .Global.Id }}-ingress-private
      ingressClassByName: true
      ingressClassResource:
        name: {{ .Global.Id }}-ingress-private
        enabled: true
        default: false
        controllerValue: k8s.io/{{ .Global.Id }}-ingress-private
      extraArgs:
        default-ssl-certificate: "{{ .Global.Id }}-ingress-private/cert-wildcard.p.{{ .Global.Domain }}"
