apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-public
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/ingress-nginx
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.PCloudEnvName }}
  interval: 1m0s
  values:
    fullnameOverride: {{ .Global.PCloudEnvName }}-ingress-public
    controller:
      kind: DaemonSet
      hostNetwork: true
      hostPort:
        enabled: true
      service:
        enabled: false
      ingressClassByName: true
      ingressClassResource:
        name: {{ .Global.PCloudEnvName }}-ingress-public
        enabled: true
        default: false
        controllerValue: k8s.io/{{ .Global.PCloudEnvName }}-ingress-public
      config:
        proxy-body-size: 100M # TODO(giolekva): configurable
    tcp:
      "53": "{{ .Global.PCloudEnvName }}-dns-zone-manager/coredns:53"
    udp:
      "53": "{{ .Global.PCloudEnvName }}-dns-zone-manager/coredns:53"
