apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/jellyfin
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    pcloudInstanceId: {{ .Global.Id }}
    ingress:
      className: {{ .Global.Id }}-ingress-private
      domain: {{ .Values.Subdomain }}.{{ .Global.PrivateDomain }}
