apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix
  namespace: {{ .Values.NamespacePrefix }}app-matrix
spec:
  chart:
    spec:
      chart: charts/matrix
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Values.Id }}
  dependsOn:
  - name: matrix-storage
    namespace: {{ .Values.NamespacePrefix }}app-matrix
  interval: 1m0s
  values:
    domain: {{ .Values.Domain }}
    oauth2:
      hydraAdmin: http://hydra-admin.{{ .Values.NamespacePrefix}}core-auth.svc.cluster.local
      hydraPublic: https://hydra.{{ .Values.Domain }}
      clientId: matrix
      clientSecret: {{ .Values.MatrixOAuth2ClientSecret }}
      secretName: oauth2-client
    postgresql:
      host: postgres
      port: 5432
      database: matrix
      user: postgres
      password: psswd
    certificateIssuer: {{ .Values.Id }}-public
    ingressClassName: {{ .Values.PCloudEnvName }}-ingress-public
    configMerge:
      configName: config-to-merge
      fileName: to-merge.yaml

