apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix
  namespace: {{ .Release.Namespace }}
spec:
  dependsOn:
  - name: matrix-storage
    namespace: {{ .Release.Namespace }}
  chart:
    spec:
      chart: charts/matrix
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    domain: {{ .Global.Domain }}
    subdomain: {{ .Values.Subdomain }}
    oauth2:
      hydraAdmin: http://hydra-admin.{{ .Global.NamespacePrefix }}core-auth.svc.cluster.local
      hydraPublic: https://hydra.{{ .Global.Domain }}
      secretName: oauth2-client
    postgresql:
      host: postgres
      port: 5432
      database: matrix
      user: matrix
      password: matrix
    certificateIssuer: {{ .Global.Id }}-public
    ingressClassName: {{ .Global.PCloudEnvName }}-ingress-public
    configMerge:
      configName: config-to-merge
      fileName: to-merge.yaml
    image:
      repository: matrixdotorg/synapse
      tag: v1.98.0
      pullPolicy: IfNotPresent
