apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-storage
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/postgresql
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    fullnameOverride: postgres
    image:
      repository: library/postgres # arm64v8/postgres
      tag: 15.3 # 13.4
    service:
      type: ClusterIP
      port: 5432
    primary:
      initdb:
        scripts:
          init.sql: |
            CREATE USER matrix WITH PASSWORD 'matrix';
            CREATE DATABASE matrix WITH OWNER = matrix ENCODING = UTF8 LOCALE = 'C' TEMPLATE = template0;
      persistence:
        size: 10Gi
      securityContext:
        enabled: true
        fsGroup: 0
      containerSecurityContext:
        enabled: true
        runAsUser: 0
    volumePermissions:
      securityContext:
        runAsUser: 0
