apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-ipaddresspool-{{ .Values.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/metallb-ipaddresspool
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 10m0s
  values:
    name: {{ .Values.Name }}
    from: {{ .Values.From }}
    to: {{ .Values.To }}
    autoAssign: {{ .Values.AutoAssign }}
    namespace: {{ .Values.Namespace }}
