apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: {{ .Values.NamespacePrefix }}app-torrent # TODO(giolekva): qbittorrent
spec:
  chart:
    spec:
      chart: charts/qbittorrent
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Values.Id }}
  dependsOn:
    - name: namespaces
      namespace: {{ .Values.Id }}
  interval: 1m0s
  values:
    pcloudInstanceId: {{ .Values.Id }}
    image:
      repository: lscr.io/linuxserver/qbittorrent
      tag: latest
      pullPolicy: IfNotPresent
    ingress:
      className: {{ .Values.Id }}-ingress-private
      domain: torrent.p.{{ .Values.Domain }}
    webui:
      port: 8080
    bittorrent:
      port: 6881
    storage:
      size: 1Ti
