apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rpuppy
  namespace: {{ .Values.NamespacePrefix }}app-rpuppy
spec:
  chart:
    spec:
      chart: charts/rpuppy
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Values.Id }}
  interval: 1m0s
  values:
    ingressClassName: pcloud-ingress-public
    certificateIssuer: lekva-public
    domain: woof.{{ .Values.Domain }}
