apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: soft-serve
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/soft-serve
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ or .Values.ChartRepositoryNamespace .Global.Id }}
  interval: 1m0s
  values:
    {{- if .Values.ServiceType }}
    serviceType: {{ .Values.ServiceType }}
    {{- end }}
    reservedIP: ""
    addressPool: {{ .Global.Id }}
    adminKey: {{ .Values.AdminKey }}
    {{- if and .Values.PrivateKey .Values.PublicKey }}
    privateKey: |
{{ .Values.PrivateKey | indent 6 }}
    publicKey: {{ .Values.PublicKey }}
    {{- end }}
    {{- if .Values.Network }}
    ingress:
      enabled: {{ .Values.Ingress.Enabled }}
      ingressClassName: {{ .Values.Network.IngressClass }}
      certificateIssuer: {{ .Values.Network.CertificateIssuer }}
      domain: {{ .Values.Subdomain }}.{{ .Values.Network.Domain }}
      {{- if .Values.SourcePort }}
      sourcePort: {{ .Values.SourcePort }}
      {{- end }}
    {{- end }}
