apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: namespaces-vaultwarden
  namespace: {{ .Global.Id }}
spec:
  chart:
    spec:
      chart: charts/namespaces
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    pcloudInstanceId: {{ .Global.Id }}
    namespacePrefix: {{ .Global.NamespacePrefix }}
    namespaces:
    - app-vaultwarden
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: {{ .Global.NamespacePrefix }}app-vaultwarden
spec:
  dependsOn:
    - name: namespaces-vaultwarden
      namespace: {{ .Global.Id }}
  chart:
    spec:
      chart: charts/vaultwarden
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    image:
      repository: vaultwarden/server
      tag: 1.28.1
      pullPolicy: IfNotPresent
    storage:
      size: 3Gi
    domain: {{ .Values.Subdomain }}.{{ .Global.PrivateDomain }}
    certificateIssuer: {{ .Global.Id }}-private
    ingressClassName: {{ .Global.Id }}-ingress-private
