apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/vaultwarden
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    image:
      repository: vaultwarden/server
      tag: 1.28.1
      pullPolicy: IfNotPresent
    storage:
      size: 3Gi
    domain: {{ .Values.Subdomain }}.{{ .Global.PrivateDomain }}
    certificateIssuer: {{ .Global.Id }}-private
    ingressClassName: {{ .Global.Id }}-ingress-private
