apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-mesh-config
  namespace: {{ .Values.NamespacePrefix }}ingress-private
spec:
  chart:
    spec:
      chart: charts/vpn-mesh-config
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Values.Id }}
  dependsOn:
  - name: namespaces
    namespace: {{ .Values.Id }}
  interval: 1m0s
  values:
    domain: {{ .Values.Domain }}
    ingressClassName: {{ .Values.PCloudEnvName }}-ingress-public
    certificateIssuer: {{ .Values.Id }}-public
    certificateAuthority:
      name: {{ .Values.Id }}
      secretName: ca-{{ .Values.Id }}-cert
    lighthouse:
      internalIP: {{ .Values.LighthouseMainIP }}
      externalIP: {{ .Values.PublicIP }}
      port: "{{ .Values.LighthouseMainPort }}"
