# TODO(giolekva): finish
apiVersion: v1
kind: Namespace
metadata:
  name: dodo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dodo-bootstrap
  namespace: dodo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dodo-bootstrap
  namespace: dodo
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dodo-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dodo-bootstrap
subjects:
- kind: ServiceAccount
  name: dodo-bootstrap
  namespace: dodo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-pub-key
  namespace: dodo
data: # TODO(giolekva): can it work without ssh-ed25519 prefix
  key.pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOa7FUrmXzdY3no8qNGUk7OPaRcIUi8G7MVbLlff9eB/
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dodo-bootstrap
  namespace: dodo
spec:
  template:
    spec:
      serviceAccountName: dodo-bootstrap
      volumes:
      - name: admin-pub-key
        configMap:
          name: admin-pub-key
      containers:
      - name: pcloud-bootstrap
        image: giolekva/pcloud-installer:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: admin-pub-key
          mountPath: /admin-pub-key
        command:
        - pcloud-installer
        - bootstrap
        - --env-name=dodo
        - --admin-pub-key=/admin-pub-key/key.pub
        - --from-ip=192.168.0.210
        - --to-ip=192.168.0.240
        - --charts-dir=/charts
        - --storage-dir=/pcloud-storage/longhorn
      restartPolicy: Never
