apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-private
    app.kubernetes.io/component: controller
  ports:
  - name: lighthouse
    port: {{ .Values.lighthouse.port }}
    targetPort: nebula
    protocol: UDP
