apiVersion: v2
name: rpuppy
version: 1.0.0
description: Renders random puppy images taken from https://dog.ceo/api
type: application
sources:
  - https://github.com/giolekva/pcloud/tree/master/apps/rpuppy
mainteners:
  - name: Giorgi Lekveishvili
    url: https://github.com/giolekva
appVersion: 1.0.0
