image:
  repository: giolekva/pcloud-installer
  tag: latest
  pullPolicy: Always
repoAddr: 192.168.0.11
sshPrivateKey: key
ingress:
  className: pcloud-ingress-public
  domain: welcome.example.com
  certificateIssuer: example-public
clusterRoleName: example-welcome
