# permissions for end users to view headscaleusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headscaleuser-viewer-role
rules:
- apiGroups:
  - headscale.dodo.cloud
  resources:
  - headscaleusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - headscale.dodo.cloud
  resources:
  - headscaleusers/status
  verbs:
  - get
