---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - headscale.dodo.cloud
  resources:
  - headscaleusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - headscale.dodo.cloud
  resources:
  - headscaleusers/finalizers
  verbs:
  - update
- apiGroups:
  - headscale.dodo.cloud
  resources:
  - headscaleusers/status
  verbs:
  - get
  - patch
  - update
