# permissions for end users to edit servicetransports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicetransport-editor-role
rules:
- apiGroups:
  - transport.dodo.cloud
  resources:
  - servicetransports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transport.dodo.cloud
  resources:
  - servicetransports/status
  verbs:
  - get
