# permissions for end users to view servicetransports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicetransport-viewer-role
rules:
- apiGroups:
  - transport.dodo.cloud
  resources:
  - servicetransports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transport.dodo.cloud
  resources:
  - servicetransports/status
  verbs:
  - get
