controller:
  image:
    repository: quay.io/metallb/controller
    tag:
    pullPolicy:
  logLevel: info
speaker:
  image:
    repository: quay.io/metallb/speaker
    tag:
    pullPolicy:
  logLevel: info
