apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.contactEmail }}
    privateKeySecretRef:
      name: issuer-{{ .Values.issuer.name }}-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.bwolf.me
          solverName: gandi
          config:
            apiKeySecretRef:
              key: api-token
              name: gandi-credentials
