apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.contactEmail }}
    privateKeySecretRef:
      name: issuer-{{ .Values.issuer.name }}-account-key
    solvers:
    - dns01:
        webhook:
          groupName: dodo.cloud # TODO(gio): configurable, this and one below
          solverName: dns-resolver-pcloud
          config:
            apiConfigMapName: {{ .Values.apiConfigMap.name }}
            apiConfigMapNamespace: {{ .Values.apiConfigMap.namespace }}
