apiVersion: v1
kind: Service
metadata:
  name: launcher
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: launcher
  ports:
    - name: {{ .Values.portName }}
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: launcher
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launcher
  template:
    metadata:
      labels:
        app: launcher
    spec:
      containers:
      - name: launcher
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        command:
        - launcher
        - --port=8080
        - --logoutUrl={{ .Values.logoutUrl }}
