apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.accessMode }}
  resources:
    requests:
      storage: {{ .Values.size }}
