apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rpuppy
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: charts/rpuppy
      sourceRef:
        kind: GitRepository
        name: pcloud
        namespace: {{ .Global.Id }}
  interval: 1m0s
  values:
    ingressClassName: {{ .Values.Network.IngressClass }}
    certificateIssuer: {{ .Values.Network.CertificateIssuer }}
    domain: {{ .Values.Subdomain }}.{{ .Values.Network.Domain }}
