{{ $prefix := .Values.namespacePrefix }}
{{ $id := .Values.pcloudInstanceId }}
{{ range .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $prefix }}{{ . }}
  labels:
    pcloud-instance-id: {{ $id }}
---
{{ end }}
