apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.oauth2.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  client_id: {{ .Values.oauth2.clientId | b64enc  }}
  client_secret: {{ .Values.oauth2.clientSecret | b64enc }}
