apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: {{ .Values.oauth2.clientId }}
  namespace: {{ .Release.Namespace }}
spec:
  grantTypes:
  - authorization_code
  responseTypes:
  - code
  scope: "openid email profile"
  secretName: {{ .Values.oauth2.secretName }}
  redirectUris:
  - https://{{ .Values.domain }}/oauth2/callback
  hydraAdmin:
    url: {{ .Values.oauth2.hydraAdmin }}
    port: 80
    endpoint: /admin/clients
    forwardedProto: https
