apiVersion: v1
kind: Service
metadata:
  name: nebula-api
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: nebula-api
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: nebula-api
  replicas: 1
  template:
    metadata:
      labels:
        app: nebula-api
    spec:
      containers:
      - name: web
        image: {{ .Values.manage.image.repository }}:{{ .Values.manage.image.tag }}
        imagePullPolicy: {{ .Values.manage.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        command:
        - nebula-api
        - --port=8080
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "20Mi"
            cpu: "100m"
      tolerations:
      - key: "pcloud"
        operator: "Equal"
        value: "role"
        effect: "NoSchedule"
