# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: www-{{ .Values.public.domain }}
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     helm.sh/resource-policy: keep
# spec:
#   dnsNames:
#   - '{{ .Values.public.domain }}'
#   - 'www.{{ .Values.public.domain }}'
#   issuerRef:
#     name: {{ .Values.public.name }}
#     kind: ClusterIssuer
#   secretName: cert-www.{{ .Values.public.domain }}
#   secretTemplate:
#     annotations:
#       kubed.appscode.com/sync: "pcloud-instance-id={{ .Values.pcloudInstanceId }}"
