apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: nats-event-source
spec:
  type: nats
  nats:
    example:
      # url of the nats service
      url: nats://nats.svc:4222
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      # subject name
      subject: input-objects
      # optional backoff time for connection retries.
      # if not provided, default connection backoff time will be used.
      connectionBackoff:
        # duration in nanoseconds. following value is 10 seconds
        duration: 10000000000
        # how many backoffs
        steps: 5
        # factor to increase on each step.
        # setting factor > 1 makes backoff exponential.
        factor: 2
        jitter: 0.2

# apiVersion: argoproj.io/v1alpha1
# kind: EventSource
# metadata:
#   name: minio-event-source
# spec:
#   type: "minio"
#   minio:
#     example:
#       bucket:
#         name: input
#       endpoint: mio-minio.default.svc:9000
#       events:
#         - s3:ObjectCreated:Put
#         - s3:ObjectRemoved:Delete
#       insecure: true
#       accessKey:
#         key: accesskey
#         name: artifacts-minio
#       secretKey:
#         key: secretkey
#         name: artifacts-minio