apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memberships
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
