apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nebulanodes.lekva.me
spec:
  group: lekva.me
  scope: Namespaced
  names:
    kind: NebulaNode
    listKind: NebulaNodeList
    plural: nebulanodes
    singular: nebulanode
    shortNames:
      - nnode
      - nnodes
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                caName:
                  type: string
                caNamespace:
                  type: string
                ipCidr:
                  type: string
                pubKey:
                  type: string
                encPubKey:
                  type: string
                secretName:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
                message:
                  type: string
