---
apiVersion: v1
kind: Namespace
metadata:
  name: app-rpuppy
---
apiVersion: v1
kind: Service 
metadata:
  name: rpuppy
  namespace: app-rpuppy
spec:
  type: ClusterIP
  selector:
    app: rpuppy
  ports:
    - nodePort: 
      port: 80
      targetPort: 1234
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: app-rpuppy
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: PathPrefix(`/rpuppy`)
    services:
    - kind: Service
      name: rpuppy
      namespace: app-rpuppy
      passHostHeader: true
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpuppy
  namespace: app-rpuppy
spec:
  selector:
    matchLabels:
      app: rpuppy
  replicas: 1
  template:
    metadata:
      labels:
        app: rpuppy
    spec:
      containers:
      - name: rpuppy
        image: giolekva/rpuppy-arm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1234
        command: ["rpuppy", "--port=1234"]
