---
apiVersion: v1
kind: Namespace
metadata:
  name: app-rpuppy
---
kind: Service 
apiVersion: v1
metadata:
  name: rpuppy
  namespace: app-rpuppy
spec:
  type: ClusterIP
  selector:
    app: rpuppy
  ports:
    - nodePort: 
      port: 80
      targetPort: 1234
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rpuppy
  namespace: app-rpuppy
spec:
  selector:
    matchLabels:
      app: rpuppy
  replicas: 1
  template:
    metadata:
      labels:
        app: rpuppy
    spec:
      containers:
      - name: rpuppy
        image: giolekva/rpuppy-arm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1234
        command: ["rpuppy", "--port=1234"]
