apiVersion: dodo.cloud.dodo.cloud/v1
kind: DNSZone
metadata:
  name: dnszone-sample
  namespace: dns-ns-controller
spec:
  zone: t5.lekva.me
  privateIP: 10.1.0.1
  publicIPs:
  - 135.181.48.180
  - 65.108.39.172
  - 65.108.39.171
  nameservers:
  - 135.181.48.180
  - 65.108.39.172
  - 65.108.39.171
