image:
  repository: headscale/headscale
  tag: 0.22.3
  pullPolicy: IfNotPresent
storage:
  size: 5Gi
ingressClassName: pcloud-ingress-public
certificateIssuer: lekva-public
domain: headscale.example.com
internalBaseDomain: p.example.com
oauth2:
  hydraAdmin: http://hydra-admin
  hydraPublic: https://hydra.example.com
  clientId: headscale
  clientSecret: ""
  secretName: oauth2-client-headscale

