image:
  repository: headscale/headscale
  tag: 0.22.3
  pullPolicy: IfNotPresent
storage:
  size: 5Gi
ingressClassName: pcloud-ingress-public
certificateIssuer: lekva-public
domain: headscale.example.com
publicBaseDomain: example.com
oauth2:
  hydraAdmin: http://hydra-admin
  hydraPublic: https://hydra.example.com
  secretName: oauth2-client-headscale
ipAddressPool: example-headscale
api:
  port: 8585
  image:
    repository: giolekva/headscale-api
    tag: latest
    pullPolicy: Always
