---
apiVersion: v1
kind: Namespace
metadata:
  name: pcloud-events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
  namespace: pcloud-events
spec:
  selector:
    matchLabels:
      app: event-processor
  replicas: 1
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
      - name: minio-importer
        image: giolekva/pcloud-event-processor:latest
        imagePullPolicy: Always
        command: ["event-processor", "--logtostderr", "--api_addr=http://api.pcloud.svc:1111/graphql", "--object_store_addr=http://minio.minio.svc:9000"]
