# permissions for end users to view dnszones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnszone-viewer-role
rules:
- apiGroups:
  - dodo.cloud.dodo.cloud
  resources:
  - dnszones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dodo.cloud.dodo.cloud
  resources:
  - dnszones/status
  verbs:
  - get
