# permissions for end users to edit dnszones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnszone-editor-role
rules:
- apiGroups:
  - dodo.cloud.dodo.cloud
  resources:
  - dnszones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dodo.cloud.dodo.cloud
  resources:
  - dnszones/status
  verbs:
  - get
