---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pcloud-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: pcloud-controller
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
---
kind: Service 
apiVersion: v1
metadata:
  name: pcloud-controller-service
spec:
  type: ClusterIP
  selector:
    app: pcloud-controller 
  ports:
    - nodePort: 
      port: 1111
      targetPort: 1234
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pcloud-controller
spec:
  selector:
    matchLabels:
      app: pcloud-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: pcloud-controller
    spec:
      serviceAccountName: pcloud-controller
      containers:
      - name: pcloud-controller
        image: pcloud-controller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1234
        volumeMounts:
        - name: code
          mountPath: /src/go/src/github.com/giolekva/pcloud/controller
        command: ["/bin/sh", "-c"]
        args: ["go run main.go --port=1234 --graphql_address=http://dgraph-public.dgraph.svc:8080/graphql --dgraph_admin_address=http://dgraph-public.dgraph.svc:8080/admin --logtostderr"]
      volumes:
      - name: code
        hostPath:
          path: "/Users/lekva/dev/go/src/github.com/giolekva/pcloud/controller"
