---
kind: Service 
apiVersion: v1
metadata:
  name: pcloud-controller-service
spec:
  type: ClusterIP
  selector:
    app: pcloud-controller 
  ports:
    - nodePort: 
      port: 1111
      targetPort: 1234
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pcloud-controller
spec:
  selector:
    matchLabels:
      app: pcloud-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: pcloud-controller
    spec:
      containers:
      - name: pfs-controller
        image: pcloud-controller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1234
        volumeMounts:
        - name: code
          mountPath: /src/go/src/github.com/giolekva/pcloud/controller
        command: ["/bin/sh", "-c"]
        args: ["go run main.go --port=1234 --graphql_address=http://dgraph-public.default.svc:8080/graphql"]
      volumes:
      - name: code
        hostPath:
          path: "/Users/lekva/dev/go/src/github.com/giolekva/pcloud/controller"
