apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-pcloud
rules:
- apiGroups:
  - dodo.cloud
  resources:
  - pcloud-dns-solver
  verbs:
  - "*" # TODO(giolekva): limit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-pcloud-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-pcloud
subjects:
- kind: ServiceAccount
  name: {{ .Values.certManager.name }}
  namespace: {{ .Values.certManager.namespace }}
