---
apiVersion: v1
kind: Namespace
metadata:
  name: app-echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: app-echo
spec:
  type: NodePort
  selector:
    app: echo
  ports:
  - port: 8080
    targetPort: 1234
    protocol: TCP
    nodePort: 32050
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ingress
#   namespace: app-echo
# spec:
#   entryPoints:
#     - web
#   routes:
#   - kind: Rule
#     match: PathPrefix(`/echo`)
#     services:
#     - kind: Service
#       name: echo
#       namespace: app-echo
#       passHostHeader: true
#       port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: app-echo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: giolekva/echo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
        command: ["echo", "--port=1234"]
