apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  - {{ .Values.from }}-{{ .Values.to }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - local
