apiVersion: v1
kind: Service
metadata:
  name: soft-serve
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if .Values.reservedIP }}
    metallb.universe.tf/loadBalancerIPs: {{ .Values.reservedIP }}
    {{ end }}
    {{ if .Values.addressPool }}
    metallb.universe.tf/address-pool: {{ .Values.addressPool }}
    {{ end }}
spec:
  type: LoadBalancer
  selector:
    app: soft-serve
  ports:
  - name: ssh
    port: {{ .Values.port }}
    protocol: TCP
  {{ if .Values.ingress.enabled }}
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  {{ end }}
