apiVersion: v1
kind: Service
metadata:
  name: soft-serve
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.reservedIP }}
spec:
  type: LoadBalancer
  selector:
    app: soft-serve
  ports:
  - name: ssh
    port: {{ .Values.port }}
    protocol: TCP
