apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soft-serve
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
